version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - mvn package
      - echo Build started
  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - target/02-spring-boot-todo-rest-api-h2-pipeline-0.0.1-SNAPSHOT.jar