version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - mvn package
      - echo Build started
  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - target/02-spring-boot-todo-rest-api-h2-pipeline-0.0.1-SNAPSHOT.jar