version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  build:
    commands:
      - export BUILD_VERSION=$(date +%Y.%m.%d).$CODEBUILD_BUILD_NUMBER
      - mvn package
      - aws elasticbeanstalk update-environment --application-name "02-spring-boot-todo-rest-api-h2-pipeline" --version-label "spring-boot-h2-02" --environment-name "02-spring-boot-todo-rest-api-h2-dev"
      - echo Build started
  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - target/02-spring-boot-todo-rest-api-h2-pipeline-0.0.1-SNAPSHOT.jar